config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index' #courses controller, index action.
  get 'courses/new', to: 'courses#new' #goes to courses controller, new action
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'logins#new' #upon receiving get login request, fire off controller 
  post 'login', to: 'logins#create' #handled by logins controller, create action
  delete 'logout', to: 'logins#destroy' #send request to logins controller, destroy action
  post 'course_enroll', to: 'student_courses#create' #post request to course enroll, to student_courses controller, create action
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, length: {minimum: 5, maximum: 50}
    validates :short_name, presence: true, length: {minimum: 3, maximum: 15}
    validates :name, presence: true, length: {minimum: 10, maximum: 300}

    has_many :student_courses
    has_many :students, through: :student_courses #link that connects in model - give a relation with student, but not directly, through student_courses
end

app/models/student.rb
class Student < ApplicationRecord
    before_save {self.email = email.downcase}
    validates :name, presence: true, length: {minimum: 5, maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 105},
        uniqueness: {case_sensitive: false},
        format: {with: VALID_EMAIL_REGEX}
    has_secure_password
    
    has_many :student_courses
    has_many :courses, through: :student_courses #link that connects in model - give a relation with course, but not directly, through student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    #this is application controller. so any restrictions will be inherited in all other controllers
    before_action :require_user

    helper_method :current_user, :logged_in?
    def current_user #in a method so we can always refer to a current user 
        @current_user ||= Student.find(session[:student_id]) if session[:student_id] # ifthis is set, then it finds student from session hash ifsession :student_id and assign it to @current_user. now there is a logged in user 
        #|| arefor memoization. the student query will only be performed ifthe @current_user does not exist
    end

    def logged_in?
        !!current_user #!! will return true or false, so returning current_user is true or false
    end

    def require_user #enforce pages and actions that require a (logged in) user
        if !logged_in? #ifnot logged in
            flash[:notice] = "You must be loggin in to perform that action"
        redirect_to login_path#then redirect
        end
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController #courses controller inheriting from app controller
    
    skip_before_action :require_user
    
    def index #directs to app/views/courses/index.html.erb
        @courses = Course.all #this make this available to all of the views
    end
    def new
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

    skip_before_action :require_user, only: [:new, :create] #will skip the :require_user actions for new and create. :require_user is inheirited from Application Controller

    def new
    end

    def create
        student = Student.find_by(email: params[:logins][:email].downcase) #grab the student
        if student && student.authenticate(params[:logins][:password]) #ifstudent exists
            session[:student_id] = student.id   #set session variable
            flash[:notice] = "You have successfully loggen in"
            redirect_to student
        else  
            flash.now[:notice] = "Something was wrong with you login information" #.now will show just on page and then leave, will not store for redirect
            render 'new'
        end
    end

    def destroy
        session[:student_id] = nil
        flash[:notice] = "You have successfully logged out"
        redirect_to root_path
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController # controller inheriting from app controller
    
    skip_before_action: :require_user
    
    def about #directs to app/pages/about.html.erb or localhost:3000/about 
    end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController 
    def create
        course_to_add = Course.find(params[:course_id]) #find the course bases on course we are sending in
        unless current_user.courses.include?(course_to_add)#create association only ifcurrent user isnt already enrolled in couse
            StudentCourse.create(course: course_to_add, student: current_user)#rails will extract id from here and use to in the association
            flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
            redirect_to current_user
        else  
            flash[:notice] = "Something was wrong with your enrollment"
            redirect_to root_path
        end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    
    skip_before_action :require_user, only: [:new, :create]
    #before_action will be applied to whatever method we specify
    #below, set_student is running from below
    before_action :set_student, only: [:show, :edit, :update]
    before_action :require_same_student, only: [:edit, :update]

    def index
        @students = Student.all
    end

    def show
        
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            flash[:sucess] = "You have successfully signed up" #display a message
            redirect_to root_path
        else 
            render 'new' #in event it doesn't work, then re-render page 
        #for whitelist, have to whitelist for created object
        end
    end

    def edit
        
    end

    def update
        @student = Student.find(params[:id])
        # using student params to white list
        if @student.update(student_params)
            flash[:sucess] = "You have successfully update your profile"
            redirect_to student_path(@student) #this could also be redirect_to @student
        else
            render 'edit'
        end
    end

    #private just means available to the this controller only
    private 

    def set_student
        @student = Student.find(params[:id])
    end

    def student_params
        params.require(:student).permit(:name, :email, :password, :password_confirmation) #this will whitelist what we receive for the web form, name and email
    end

    def require_same_student
        if current_user != @student #ifthe current user is not the same as the student object, then redirect to their own profile
        flash[:notice] = "You can only edit your own profile"
            redirect_to student_path(current_user)
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def session_link
        if (logged_in?)
            link_to "logout", logout_path, method: :delete # only need to declare method for delete 
        else 
            link_to "login", login_path 
        end 
    end 
end

app/views/courses/index.html.erb
<div class='row'>
    <div class='col s12 center-align'>
        <h3>Course Listings</h3>
    </div>
</div>

<div class="row">
    <% @courses.each do |course| %>
        <div class="col s6 m6">
            <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title"><%=course.short_name%></span>
                <p><%=course.description%></p>
            </div>
            <div class="card-action">
                <%# #if logged_in and the current user already is enrolled in the course %>
                <% if logged_in? && !(current_user.courses.include?(course))%> 
                <%# have to specify method post (not using a form for helper) %>
                    <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %> <%# passing in course_id param (one of the keys in the params hash) and the value of the id of the course%>
                <% end %>
                    <a href="#">Info</a>
                    <%= link_to 'download via link_to', 'file.txt', download: '' %>
                    <a href="file.txt" download>Download via a href</a>

            </div>
            </div>
        </div>
    <%end%>
</div>

app/views/courses/new.html.erb
<h1>This is the new course page</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
    <div class="container">
    <div class="row">
        <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">Some paragraph text here</p>
        </div>
        <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
        </div>
    </div>
    </div>
    <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
    <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
        <li><%= link_to "View your profile", student_path(current_user)%></li>
    <% end %>
    <li class="divider"></li>
 
    </ul>
    <ul id="dropdown2" class="dropdown-content">
    <li><%= session_link %></li>
    <% if logged_in? %>
        <li><%= link_to "View your profile", student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
    </ul>
    <nav>
    <div class="container">
        <div class="nav-wrapper">
        <%= link_to "Tech University", root_path, class: "brand-logo right" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><%= link_to 'Courses', root_path %></li>
            <% if logged_in? %>
                <li><%= link_to 'Students', students_path %></li>
            <% end %>
            <li><%= link_to 'New', courses_new_path %></li>
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right"></i></a></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
            <li><%= link_to "Courses", root_path%></li>
            <li><a href="#">Enrollment</a></li>
            <li><a href="#">Account</a></li>
            <li><a class="dropdown-trigger2" href="#!" data-target="dropdown2">Account<i class="material-icons right"></i></a></li>
        </ul>
        </div>
    </div>
    </nav>
    <% flash.each do |key, message|%>
        <div class = "container">
            <div class= "row sign-up-form">
                <div class="col s12 m12 l12">
                    <div class="card-panel red lighten-2" id="fade-out-target">
                        <span class= "white-text">
                            <%= message %>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>University App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <%# application.js file is then available to all the views. %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
    <div class="row center sign-up-form">
        <div class="row center">
            <div class="col s12 m12 l12">
                <div class="card-panel">
                    <%# if @student instance variable is a new record ? then :  %>
                    <h3>Login</h3>
                    <div class="row"> 
                    <%# model backed forms allow grabbing database object based on the id of the student %>
                        <%= form_for(:logins, html: {class: "col s12"}) do |f| %>
                        
                            <div class="row">
                                <div class= "input-field col s12">
                                    <%= f.text_field :email, placeholder: "Email", autofocus: true %>
                                    <%= f.label :email %>
                                </div>
                            </div>
                            <div class="row">
                                <div class= "input-field col s12">
                                    <%= f.password_field :password, placeholder: "Enter your password", autofocus: true %>
                                    <%= f.label :password, class: "active" %>
                                </div>
                            </div>
                            <div class="row">
                                <div class= "input-field col s12">
                                <%# if @student instance variable is a new record %>
                                <%# if is new record show sign up OTHERWISE ? show : submit changes %>
                                    <%= f.button '<i class="material-icons right">arrow_forward</i>Log In'.html_safe , class: "btn light-blue waves-effect waves-light right" %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>The is the about page</h1>

app/views/shared/_errors.html.erb
<%# obj can be anything %>
<%if obj.errors.any? %>
    <div class = "container">
        <div class= "row sign-up-form">
            <div class="col s12 m12 l12">
                <div class="card-panel red lighten-2">
                    <span class= "white-text">
                        <%= pluralize(obj.errors.count, "error")%>
                        Prohibited your profile from being created
                        <ul>
                        <%@student.errors.full_messages.each do |message| %>
                            <li><%= message %>
                            <% end %>
                        </ul>
                        <% end %>
                    </span>
                </div>    
            </div>   
        </div>   
    </div>   

app/views/students/_form.html.erb
<%# have to specify what obj is (for the shared errors partial) %>
<%= render 'shared/errors', obj: @student %> 
<div class="container">
    <div class="row center sign-up-form">
        <div class="row center">
            <div class="col s12 m12 l12">
                <div class="card-panel">
                    <%# if @student instance variable is a new record ? then :  %>
                    <h3><%= @student.new_record? ? "Create Your Profile" : "Edit your profile"%></h3>
                    <div class="row"> 
                    <%# model backed forms allow grabbing database object based on the id of the student %>
                        <%= form_for(@student, html: {class: "col s12"}) do |f| %>
                            <div class="row">
                                <div class= "input-field col s12">
                                    <%= f.text_field :name, placeholder: "Full Name", autofocus: true %>
                                    <%= f.label :name, class: "active" %>
                                </div>
                            </div>
                            <div class="row">
                                <div class= "input-field col s12">
                                    <%= f.text_field :email, placeholder: "Email", autofocus: true %>
                                    <%= f.label :email, class: "active" %>
                                </div>
                            </div>
                            <div class="row">
                                <div class= "input-field col s12">
                                    <%= f.password_field :password, placeholder: "Enter a password", autofocus: true %>
                                    <%= f.label :password, class: "active" %>
                                </div>
                            </div>
                            <div class="row">
                                <div class= "input-field col s12">
                                    <%= f.password_field :password_confirmation, placeholder: "Confirm password", autofocus: true %>
                                    <%= f.label :password_confirmation, class: "active" %>
                                </div>
                            </div>
                            <div class="row">
                                <div class= "input-field col s12">
                                <%# if @student instance variable is a new record %>
                                <%# if is new record show sign up OTHERWISE ? show : submit changes %>
                                    <%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign Up'.html_safe : '<i class="material-icons right">arrow_forward</i>Submit Changes'.html_safe, class: "btn light-blue waves-effect waves-light right" )%>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/edit.html.erb
<%= render 'form'%>

app/views/students/index.html.erb
<div class='row'>
    <div class='col s12 center-align'>
        <h3>Student Directory</h3>
    </div>
</div>

<div class="row">
    <% @students.each do |s| %>
        <div class="col s6 m6">
            <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title">Name: <%=s.name%></span>
                <p>Email: <%=s.email%></p>
                <p>Course Enrollments:</p>
            </div>
            <div class="card-action">
                <%= link_to "View profile", student_path(s) %>
            </div>
            </div>
        </div>
    <%end%>
</div>

app/views/students/new.html.erb
<%= render 'form'%>

app/views/students/show.html.erb
<div class='row sign-up-form'>
    <div class='col s12 center-align'>
        <h3>Student Directory</h3>
    </div>
</div>

<div class="row">
    <div class="col s6 m6">
        <div class="card blue-grey darken-1">
        <div class="card-content white-text">
            <span class="card-title">Name: <%=@student.name%></span>
            <p>Email: <%=@student.email%></p>
            <p>Current enrollements:
                <% if @student.courses.empty? %>
                    None
                <% else %>
                    <ul>
                        <% @student.courses.each do |course| %>
                            <li><%= course.name %></li>
                        <% end %>
                    </ul>
                    <% end %>
                </p>
            </div>
        </div>
        <%# if the current user is the same as the student on this page, show the link %>
        <% if current_user == @student %> 
            <%= link_to '<i class="material-icons right">cloud</i>Edit your profile'.html_safe, edit_student_path(@student), class:"waves-effect waves-light btn"%>
        <% end %>
    </div>
</div>